name: clean_architecture
description: A Flutter Project with clean architecture implementation

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13
  #build runner
  build_runner: ^2.4.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
